from __future__ import annotations

from typing import Protocol

from src.brokers.models import (
    BrokerAccount,
    BrokerCancelResult,
    BrokerHealth,
    BrokerOrder,
    BrokerOrderSubmission,
    BrokerPosition,
    EntryOrderRequest,
    ExitOrderRequest,
)


class BrokerAdapter(Protocol):
    broker_name: str

    async def get_account(self) -> BrokerAccount: ...
    async def get_positions(self) -> list[BrokerPosition]: ...
    async def get_order(self, broker_order_id: str, *, nested: bool = False) -> BrokerOrder | None: ...
    async def list_open_orders(self) -> list[BrokerOrder]: ...
    async def submit_market_entry(self, request: EntryOrderRequest) -> BrokerOrderSubmission: ...
    async def submit_market_exit(self, request: ExitOrderRequest) -> BrokerOrderSubmission: ...
    async def cancel_order(self, broker_order_id: str) -> BrokerCancelResult: ...
    async def supports_bracket_orders(self) -> bool: ...
    async def healthcheck(self) -> BrokerHealth: ...
